2014-11-30T08:52:27.463144+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
2014-11-30T08:52:27.463146+00:00 app[web.1]:     self._setup(name)
2014-11-30T08:52:27.463147+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
2014-11-30T08:52:27.463148+00:00 app[web.1]:     self._wrapped = Settings(settings_module)
2014-11-30T08:52:27.463150+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 94, in __init__
2014-11-30T08:52:27.463152+00:00 app[web.1]:     mod = importlib.import_module(self.SETTINGS_MODULE)
2014-11-30T08:52:27.463153+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
2014-11-30T08:52:27.463155+00:00 app[web.1]:     __import__(name)
2014-11-30T08:52:27.463095+00:00 app[web.1]:     mod = importlib.import_module(self.SETTINGS_MODULE)
2014-11-30T08:52:27.463157+00:00 app[web.1]:     DATABASES['default'] =  dj_database_url.config()
2014-11-30T08:52:27.463122+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
2014-11-30T08:52:27.463123+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-11-30T08:52:27.463227+00:00 app[web.1]: [2014-11-30 08:52:27 +0000] [7] [INFO] Worker exiting (pid: 7)
2014-11-30T08:52:27.463159+00:00 app[web.1]: NameError: name 'DATABASES' is not defined
2014-11-30T08:52:27.463099+00:00 app[web.1]:   File "/app/hellodjango/settings.py", line 65, in <module>
2014-11-30T08:52:27.463100+00:00 app[web.1]:     DATABASES['default'] =  dj_database_url.config()
2014-11-30T08:52:27.463102+00:00 app[web.1]: NameError: name 'DATABASES' is not defined
2014-11-30T08:52:27.463103+00:00 app[web.1]: Traceback (most recent call last):
2014-11-30T08:52:27.599738+00:00 app[web.1]: [2014-11-30 08:52:27 +0000] [2] [INFO] Reason: Worker failed to boot.
2014-11-30T08:52:27.463104+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2014-11-30T08:52:27.463106+00:00 app[web.1]:     worker.init_process()
2014-11-30T08:52:27.599598+00:00 app[web.1]: [2014-11-30 08:52:27 +0000] [2] [INFO] Shutting down: Master
2014-11-30T08:52:27.463140+00:00 app[web.1]:     django.setup()
2014-11-30T08:52:27.463156+00:00 app[web.1]:   File "/app/hellodjango/settings.py", line 65, in <module>
2014-11-30T08:52:27.505014+00:00 heroku[web.1]: State changed from starting to up
2014-11-30T08:52:28.380876+00:00 heroku[web.1]: Process exited with status 3
2014-11-30T08:52:28.392140+00:00 heroku[web.1]: State changed from up to crashed
2014-11-30T08:52:28.392576+00:00 heroku[web.1]: State changed from crashed to starting
2014-11-30T08:52:33.095869+00:00 heroku[web.1]: Starting process with command `gunicorn hellodjango.wsgi --log-file -`
2014-11-30T08:52:34.923454+00:00 app[web.1]: [2014-11-30 08:52:34 +0000] [2] [INFO] Starting gunicorn 19.1.1
2014-11-30T08:52:34.925309+00:00 app[web.1]: [2014-11-30 08:52:34 +0000] [2] [INFO] Using worker: sync
2014-11-30T08:52:34.924693+00:00 app[web.1]: [2014-11-30 08:52:34 +0000] [2] [INFO] Listening at: http://0.0.0.0:50437 (2)
2014-11-30T08:52:34.938991+00:00 app[web.1]: [2014-11-30 08:52:34 +0000] [7] [INFO] Booting worker with pid: 7
2014-11-30T08:52:35.518223+00:00 heroku[web.1]: State changed from starting to up
2014-11-30T08:52:35.768218+00:00 app[web.1]: [2014-11-30 08:52:35 +0000] [7] [ERROR] Exception in worker process:
2014-11-30T08:52:35.768225+00:00 app[web.1]: Traceback (most recent call last):
2014-11-30T08:52:35.768228+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2014-11-30T08:52:35.768229+00:00 app[web.1]:     worker.init_process()
2014-11-30T08:52:35.768231+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
2014-11-30T08:52:35.768233+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-11-30T08:52:35.768234+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
2014-11-30T08:52:35.768236+00:00 app[web.1]:     self.callable = self.load()
2014-11-30T08:52:35.768237+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2014-11-30T08:52:35.768239+00:00 app[web.1]:     return self.load_wsgiapp()
2014-11-30T08:52:35.768240+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2014-11-30T08:52:35.768242+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-11-30T08:52:35.912544+00:00 app[web.1]: [2014-11-30 08:52:35 +0000] [2] [INFO] Shutting down: Master
2014-11-30T08:52:35.768244+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 356, in import_app
2014-11-30T08:52:35.768245+00:00 app[web.1]:     __import__(module)
2014-11-30T08:52:35.768247+00:00 app[web.1]:   File "/app/hellodjango/wsgi.py", line 16, in <module>
2014-11-30T08:52:35.768248+00:00 app[web.1]:     application = Cling(get_wsgi_application())
2014-11-30T08:52:35.768250+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
2014-11-30T08:52:35.768251+00:00 app[web.1]:     django.setup()
2014-11-30T08:52:35.768252+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/__init__.py", line 20, in setup
2014-11-30T08:52:35.768254+00:00 app[web.1]:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2014-11-30T08:52:35.768255+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
2014-11-30T08:52:35.768257+00:00 app[web.1]:     self._setup(name)
2014-11-30T08:52:35.768258+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
2014-11-30T08:52:35.768259+00:00 app[web.1]:     self._wrapped = Settings(settings_module)
2014-11-30T08:52:35.768260+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 94, in __init__
2014-11-30T08:52:35.768266+00:00 app[web.1]:   File "/app/hellodjango/settings.py", line 65, in <module>
2014-11-30T08:52:35.768267+00:00 app[web.1]:     DATABASES['default'] =  dj_database_url.config()
2014-11-30T08:52:35.768262+00:00 app[web.1]:     mod = importlib.import_module(self.SETTINGS_MODULE)
2014-11-30T08:52:35.768263+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
2014-11-30T08:52:35.768265+00:00 app[web.1]:     __import__(name)
2014-11-30T08:52:35.768270+00:00 app[web.1]: Traceback (most recent call last):
2014-11-30T08:52:35.768271+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2014-11-30T08:52:35.768273+00:00 app[web.1]:     worker.init_process()
2014-11-30T08:52:35.768269+00:00 app[web.1]: NameError: name 'DATABASES' is not defined
2014-11-30T08:52:35.768296+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2014-11-30T08:52:35.768297+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 66, in wsgi
2014-11-30T08:52:35.768298+00:00 app[web.1]:     self.callable = self.load()
2014-11-30T08:52:35.768294+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 114, in init_process
2014-11-30T08:52:35.768300+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2014-11-30T08:52:35.768301+00:00 app[web.1]:     return self.load_wsgiapp()
2014-11-30T08:52:35.768302+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2014-11-30T08:52:35.768303+00:00 app[web.1]:     return util.import_app(self.app_uri)
2014-11-30T08:52:35.768305+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 356, in import_app
2014-11-30T08:52:35.768306+00:00 app[web.1]:     __import__(module)
2014-11-30T08:52:35.768307+00:00 app[web.1]:   File "/app/hellodjango/wsgi.py", line 16, in <module>
2014-11-30T08:52:35.768309+00:00 app[web.1]:     application = Cling(get_wsgi_application())
2014-11-30T08:52:35.768310+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
2014-11-30T08:52:35.768314+00:00 app[web.1]:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2014-11-30T08:52:35.768316+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
2014-11-30T08:52:35.768317+00:00 app[web.1]:     self._setup(name)
2014-11-30T08:52:35.768318+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
2014-11-30T08:52:35.768311+00:00 app[web.1]:     django.setup()
2014-11-30T08:52:35.768313+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/__init__.py", line 20, in setup
2014-11-30T08:52:35.768320+00:00 app[web.1]:     self._wrapped = Settings(settings_module)
2014-11-30T08:52:35.768321+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 94, in __init__
2014-11-30T08:52:35.768322+00:00 app[web.1]:     mod = importlib.import_module(self.SETTINGS_MODULE)
2014-11-30T08:52:35.768324+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
2014-11-30T08:52:35.768326+00:00 app[web.1]:     __import__(name)
2014-11-30T08:52:35.768327+00:00 app[web.1]:   File "/app/hellodjango/settings.py", line 65, in <module>
2014-11-30T08:52:35.768328+00:00 app[web.1]:     DATABASES['default'] =  dj_database_url.config()
2014-11-30T08:52:35.768330+00:00 app[web.1]: NameError: name 'DATABASES' is not defined
2014-11-30T08:52:35.769384+00:00 app[web.1]: [2014-11-30 08:52:35 +0000] [7] [INFO] Worker exiting (pid: 7)
2014-11-30T08:52:35.912736+00:00 app[web.1]: [2014-11-30 08:52:35 +0000] [2] [INFO] Reason: Worker failed to boot.
2014-11-30T08:52:36.767380+00:00 heroku[web.1]: Process exited with status 3
2014-11-30T08:52:36.783397+00:00 heroku[web.1]: State changed from up to crashed
2014-11-30T08:52:53.250028+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=pacific-inlet-2042.herokuapp.com request_id=078463b6-d3e5-4a67-8878-92a80cf8648a fwd="89.201.236.237" dyno= connect= service= status=503 bytes=
